name: check

on: pull_request_target

jobs:
  check:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
      - name: Checkout PR branch
        run: |
          git remote add pr ${{ github.event.pull_request.head.repo.html_url }}
          git fetch pr
          git switch -c pr/${{ github.event.pull_request.head.ref }} pr/${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Check Problems in Code
        # TODO: https://github.community/t/sanitizing-quotes-in-pr-titles/169175/6
        run: >
          curl --location --fail --silent --show-error -o code-checker.jar https://github.com/ByteLegend/tools/releases/download/v1.0.0/code-checker.jar &&
          java
          -DprRepoFullName=${{ github.event.pull_request.base.repo.full_name }}
          -DprAuthor=${{ github.event.pull_request.user.login }}
          -DprNumber=${{ github.event.pull_request.number }}
          -DprTitle='${{ github.event.pull_request.title }}'
          -DprHeadSha=${{ github.event.pull_request.head.sha }}
          -DapiUrl=https://bytelegend.com
          -DcodeCheckerSecret=${{ secrets.CODE_CHECKER_SECRET }}
          -jar code-checker.jar
      - name: Verify
        run: bash -e -x ./check.sh
      - name: Merge and Revert
        run: >
          curl --location --fail --silent --show-error -o code-checker.jar https://github.com/ByteLegend/tools/releases/download/v1.0.0/code-checker.jar &&
          java
          -DprRepoFullName=${{ github.event.pull_request.base.repo.full_name }}
          -DprAuthor=${{ github.event.pull_request.user.login }}
          -DprNumber=${{ github.event.pull_request.number }}
          -DprTitle='${{ github.event.pull_request.title }}'
          -DprHeadSha=${{ github.event.pull_request.head.sha }}
          -DpushUrl=-DrepoPushUrl=https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.event.pull_request.base.repo.full_name }}.git
          -jar code-merger.jar
